//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editroid.ROM.Enhanced {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnhancerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnhancerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Editroid.ROM.Enhanced.EnhancerResources", typeof(EnhancerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] NMI_Hijack_unused {
            get {
                object obj = ResourceManager.GetObject("NMI_Hijack_unused", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; NO LONGER USED
        ///; NO LONGER USED
        ///; NO LONGER USED
        ///; NO LONGER USED
        ///; NO LONGER USED
        ///; NO LONGER USED
        ///; NO LONGER USED
        ///; NO LONGER USED
        ///; NO LONGER USED
        ///; NO LONGER USED
        ///
        ///; This code has been included in a single ASM file to avoid issues with syncing multiple files.
        ///
        ///; Simple one-liner that hijacks the NMI routine to perform CHR bank swapping during NMI
        ///
        ///; .org $C106
        ///
        ///.PATCH 0F:C106
        ///JMP $C669   ; If the location of the bank cycling code changes, this needs to be updated..
        /// </summary>
        internal static string NmiHijack_ASM_unused {
            get {
                return ResourceManager.GetString("NmiHijack_ASM_unused", resourceCulture);
            }
        }
        
        internal static byte[] PPU_Loader_unused {
            get {
                object obj = ResourceManager.GetObject("PPU_Loader_unused", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; ===============================================================
        ///; Enable 4kb CHR bank swapping (separate SPR and BGR)
        ///; ===============================================================
        ///.PATCH 0F:C06D
        ///
        ///;LC06D:	lda #%00001110			;Verticle mirroring.
        ///        LDA #%00011110                  ;Verticle mirroring + 4kb swapping 
        ///
        ///
        ///;            const byte ChrSwapMode_4k = 0x10;
        ///;            const int ChrSwapSize_Offset = 0x3C07E;
        ///;            
        ///;            enhancedRomData[ChrSwapSize_Offset] |= ChrSwapM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PpuLoader_ASM {
            get {
                return ResourceManager.GetString("PpuLoader_ASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;  _____________________________
        ///; |=============================|
        ///; ||‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾||
        ///; || ROOM DATA HACK            || 
        ///; ||___________________________||
        ///; |=============================|
        ///;  ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
        ///
        ///; ================================
        ///; Defines
        ///; ================================
        ///NMIStatus		:=	$1A	
        ///CurrentBank		:=	$23
        ///RoomPtr			:=	$33
        ///RoomNumber		:=	$5A
        ///StructPtr       :=  $35
        ///MacroPtr        :=  $3F
        ///AddYToPtr00     :=  $C2A8
        ///TilePosTable    :=  $EF9A
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RoomDataHack {
            get {
                return ResourceManager.GetString("RoomDataHack", resourceCulture);
            }
        }
    }
}
