//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editroid.ROM.Projects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Editroid.ROM.Projects.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Defines File
        ///;
        ///; Include your variable, constant, and label declarations here
        ///;
        ///; By default, this file contains two parts: (1) Label declarations derived
        ///; from SnowBro/Dirty McDingus&apos; Metroid Disassembly, and (2) Variable (RAM)
        ///; declarations taken directly from the same document.
        ///
        ///
        ///;----------------------------------------------------------------------------
        ///; Game engine bank routines
        ///;----------------------------------------------------------------------------
        ///; Addresses derived from Sno [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultDefinesFile {
            get {
                return ResourceManager.GetString("DefaultDefinesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; General Code File
        ///; ------- ---- ----
        ///; Put any routines/data here that is used by your 
        ///; screen-load ASM. The general code file is assembled
        ///; and copied to every level data bank.
        ///
        ///; READ BELOW FOR HANDY INFO ON EDITROID PROJECTS!
        ///
        ///; Note that your ROM and project will be saved each
        ///; time you build the project. The project (ASM and
        ///; related settings) will be saved in a .nes.proj file.
        ///
        ///; The &quot;Save &amp; Play&quot; feature will launch your ROM without 
        ///; applying any ASM. If you want to test the RO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultGeneralFile {
            get {
                return ResourceManager.GetString("DefaultGeneralFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Edtroid 3.5
        ///; Main Project File
        ///;
        ///; This file contains the code needed to allow the game to use
        ///; CHR ROM and extra data banks.
        ///
        ///
        ///
        ///
        ///; ================================
        ///; Variables
        ///; ================================
        ///
        ///    
        ///    RoomDataBanked      :=	$7810
        ///    BankSwapLock        :=  $7811
        ///
        ///
        ///; ================================
        ///; Updated Pointers
        ///; ================================
        ///
        ///; Pointers to structures and combos
        ///.PATCH 01:959C
        ///		.DW	$8400	; Structure table
        ///		.DW $8000	; Combo table [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultMainFile {
            get {
                return ResourceManager.GetString("DefaultMainFile", resourceCulture);
            }
        }
    }
}
